spring:
  security:
     oauth2:
       client:
         registration:
             google:
                clientId: 790060906781-cpnvpmmj9llqf5hphjqftnb41iusg4d2.apps.googleusercontent.com
                clientSecret: QjoiZcBgfWeh8uuBH5IMMoiI 