server:
 port: 9761


file:
 storage:
   location: D:\FIle-handle-storage

spring:
 servlet:
   multipart:
     enabled: true
     location: D:\file-handle-temporary-store
     file-size-threshold: 5MB
     max-file-size: 5MB
     max-request-size: 30MB